# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Possum House Games
subtitle: We make games.
url: https://possumhousegames.com
email:
description: >- # this means to ignore newlines until "baseurl:"
    Possum House is an indie development studio that focuses on small titles with experimental and fresh mechanics. With each game we try to introduce something novel and unique that players haven’t seen before. We want to be a sustainable and experimental team that puts the medium first, allowing us to develop unique titles. Less is more is our approach. Aesthetics > graphics. Simple mechanics arranged in original ways.
twitter_username: PossumHGames
github_username: possumhousegames
minimal_mistakes_skin: dark
search: false

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show 
paginate_path: /recent/page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
logo: "/assets/images/whitelogo.png"
masthead_title: "Possum House Games"
include:
  - _pages

# Analytics
analytics:
  provider               : google # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : UA-176073293-1
    anonymize_ip         : # true, false (default)

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

author:
  name   : "Possum House Games"
  avatar : "/assets/images/collaborators/PossumHouse.png"
  bio    : "We make games."
  subtitle : "Indie Game Studio"
  # twitter: PossumHGames
  # steam: PossumHouse
  email: possumHgames@gmail.com
  # facebook: Possum-House-Games-105905267566976
  # instagram: funnybirdart
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://possumhousegames.com/"
    - label: "Itch.io"
      icon: "fab fa-fw fa-itch-io"
      url: "https://possumhousegames.itch.io/"
    - label: "Steam"
      icon: "fab fa-fw fa-steam"
      url: "https://store.steampowered.com/search/?developer=Possum%20House%20Games"
    # - label: "Steam Profile"
    #   icon: "fas fa-fw fa-steam"
    #   url: "https://steamcommunity.com/profiles/76561198979349660/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/PossumHGames"
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/funnybirdart/"    
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UCbCQ7FJ-OSXulMFavJyKsPQ"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/Possum-House-Games-105905267566976"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/RmFFxyw"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _games
  - scope:
      path: ""
      type: games
    values:
      layout: game
      author_profile: false
      share: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

games_archive:
  type: liquid
  path: /games/


# Collections
collections:
  games:
    output: true
    permalink: /:collection/:path/

# Site Footer
footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://possumhousegames.com/"
    - label: "Itch.io"
      icon: "fab fa-fw fa-itch-io"
      url: "https://possumhousegames.itch.io/"
    - label: "Steam"
      icon: "fab fa-fw fa-steam"
      url: "https://store.steampowered.com/search/?developer=Possum%20House%20Games"
    # - label: "Steam Profile"
    #   icon: "fas fa-fw fa-steam"
    #   url: "https://steamcommunity.com/profiles/76561198979349660/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/PossumHGames"
    # - label: "GitHub"
    #   icon: "fab fa-fw fa-github"
    #   url: "https://github.com/"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/funnybirdart/"    
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UCbCQ7FJ-OSXulMFavJyKsPQ"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/Possum-House-Games-105905267566976"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "https://discord.gg/RmFFxyw"